### ISSUE TITLE
The 'vars' file was not found

### ISSUE THREAD

**Issue by vanodevium** [chadoe/docker-openvpn#15]
docker-compose.yml
```yml
version: "3.9"

services:

  vpn:
    image: "martin/openvpn"
    container_name: "vpn"
    restart: always
    env_file: ".env"
    volumes:
      - "./config:/etc/openvpn"
      - "/etc/localtime:/etc/localtime:ro"
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"

```

When I start command

```sh
docker-compose run --rm vpn initopenvpn -u udp://"${IP}" -d
```

Receive
```shell
Easy-RSA error:

The 'vars' file was not found:
* /etc/openvpn/vars

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | nix | Linux | undefined
```
